name: run-tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        inertia: [^1.0, ^2.0]
        laravel: [10.*, 11.*, 12.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: ^8
            phpunit-config: phpunit.10.xml.dist
          - laravel: 11.*
            testbench: ^9
            phpunit-config: phpunit.xml.dist
          - laravel: 12.*
            testbench: ^10
            phpunit-config: phpunit.xml.dist
        exclude:
          # Inertia 1.x support for Laravel 12 hasn't landed yet, can probably be removed if 1.4.0 is released
          - inertia: ^1.0
            laravel: 12.*

    name: PHP${{ matrix.php }} - L${{ matrix.laravel }} - Inertia ${{ matrix.inertia }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "inertiajs/inertia-laravel:${{ matrix.inertia }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --no-coverage --configuration ${{ matrix.phpunit-config }}
